language: node_js
node_js: lts/*

cache:
  directories:
    - ~/.rvm/gems
    - node_modules

install:
  - npm install
  - npm start >/dev/null &
  - gem install cucumber rspec capybara selenium-webdriver chromedriver-helper
